### ISSUE TITLE
Crashing at color game iphone 4

### ISSUE THREAD

**Issue by wrongnumb3r** [Navideck/Romo-X#7]
I have tried 2 iphone 4's and both crash when we zoom into the robot's eye and it states "this is how I see the world".

Both iphone 4
One is model MC318LL/A
The other is MD127LL/A
Both are running iOS 7.1.2
Both are running the latest compatible version of the app, installed today from the app store.

I have checked permissions.  It asks for permission for photos, both were granted permission.  

Let me know what other information I can provide.
Thank you for breathing new life into my Romo, I was just about to dismantle it.

**Comment by fotiDim** [comment]
Hi and thanks for the report. Being on iOS 7 it makes it a bit tough to debug. Can you try locating the "Romo" crash reports under "General->About->Diagnostics & Usage->Diagnostics & Usage Data" and uploading them?

Do you have the chance to test on a newer phone with iOS 9+ to see if the issue is still there?

**Comment by wrongnumb3r** [comment]
Thank you.  Here is the crash report.
[Romo_crash.txt](https://github.com/Navideck/Romo/files/6178523/Romo_crash.txt)

Unfortunately I have the romo with the 30 pin connector so i'm unable to try the newer phone. I may look into getting an adapter and test it out then.

**Comment by fotiDim** [comment]
The crash report was useful. It seems to be something related to the camera frame rate. I will try to reproduce it over the next days and create a fix. Note though the the current app on the App Store supports iOS 9+ which means if you have the 30 pin version only the iPhone 4S will work. Nevertheless, I will have a look into back-porting the app to iOS 7 again.

**Comment by wrongnumb3r** [comment]
Excellent.  Thank you.

**Comment by fotiDim** [comment]
I spotted the problem and have the fix ready. The problem now is to issue a new release that also supports iOS 7. We have to jump through multiple hoops for this. I am investigating how this can be done. Sit tight.

**Comment by fotiDim** [comment]
Quick update: I have done great progress with this and there is only one small issue remaining. iPhone 4 cannot handle the size of the assets bundle. I am trying to shrink it down currently so that is plays nice with all iPhone models. So overall good news. It is only a matter of time now before we can support iPhone 4 & iOS 7 with the latest version of the app.

**Comment by fotiDim** [comment]
@wrongnumb3r version 2.3 is now released on the App Store with official iOS 7 support and the fix for the mentioned crash. I needed to overcome many obstacles for this release to happen, as supporting such old iOS versions is quite difficult nowadays. Nevertheless we managed to pull through! 💪

Feel free to reopen if you are still experiencing the crash.

**Comment by wrongnumb3r** [comment]
Thank you very much.  I will let you know if there are any issues.
